
/*!
 * Module dependencies.
 */

// Note: We can require users, articles and other cotrollers because we have
// set the NODE_PATH to be ./app/controllers (package.json # scripts # start)

/*
fs  =require('fs');
var join = require('path').join;

fs.readdirSync( './app/controllers').forEach(function (file) {
  if (~file.indexOf('.js')) require(join( './app/controllers', file));
});

*/
var users = require('../app/controllers/users.js');
var articles = require('../app/controllers/articles.js');
var messages = require('../app/controllers/messages.js');
var comments = require('../app/controllers/comments.js');
var welcome = require('../app/controllers/welcome.js');
var api = require('../app/controllers/api.js');
var tags = require('../app/controllers/tags.js');
var angularData = require('../app/controllers/angularData.js');

var auth = require('./middlewares/authorization');



//generated controllers 
	var learnMore = require('../app/genControllers/learnMore.js');
	 
	var recentlySearched = require('../app/genControllers/recentlySearched.js');
	 
	var result = require('../app/genControllers/result.js');
	 
	var search = require('../app/genControllers/search.js');
	 
	var detail = require('../app/genControllers/detail.js');
	 
	var recentlyViewed = require('../app/genControllers/recentlyViewed.js');
	 
	var myAccount = require('../app/genControllers/myAccount.js');
	 
	var browse = require('../app/genControllers/browse.js');
	 
	var photo = require('../app/genControllers/photo.js');
	 
	var coder = require('../app/genControllers/coder.js');
	

//end generated controllerers

try{
var generator = require('../config/generator/viewSwatches.js');
var mobileGenerator = require('../config/generator/mobileCreate.js');
}
catch(err){
  console.log('This app was generated by CodeSwatch');
}

/**
 * Route middlewares
 */

var articleAuth = [auth.requiresLogin, auth.article.hasAuthorization];

var commentAuth = [auth.requiresLogin, auth.comment.hasAuthorization];

/**
 * Expose routes
 */

module.exports = function (app, passport) {

  // user routes
  app.get('/login', users.login);
  app.get('/signup', users.signup);
  app.get('/logout', users.logout);
  app.post('/users', users.create);
  app.post('/users/session',
    passport.authenticate('local', {
      failureRedirect: '/login',
      failureFlash: 'Invalid email or password.'
    }), users.session);
   app.get('/me', users.info);

    app.get('/users/:userId/edit', users.edit);
     app.put('/users/:userId', users.update);
      app.post('/users/:userId', users.update);
  app.get('/users/:userId', users.show);
  app.get('/auth/facebook',
    passport.authenticate('facebook', {
      scope: [ 'email', 'user_about_me'],
      failureRedirect: '/login'
    }), users.signin);
  app.get('/auth/facebook/callback',
    passport.authenticate('facebook', {
      failureRedirect: '/login'
    }), users.authCallback);
  app.get('/auth/github',
    passport.authenticate('github', {
      failureRedirect: '/login'
    }), users.signin);
  app.get('/auth/github/callback',
    passport.authenticate('github', {
      failureRedirect: '/login'
    }), users.authCallback);
  app.get('/auth/twitter',
    passport.authenticate('twitter', {
      failureRedirect: '/login'
    }), users.signin);
  app.get('/auth/twitter/callback',
    passport.authenticate('twitter', {
      failureRedirect: '/login'
    }), users.authCallback);
  app.get('/auth/google',
    passport.authenticate('google', {
      failureRedirect: '/login',
      scope: [
        'https://www.googleapis.com/auth/userinfo.profile',
        'https://www.googleapis.com/auth/userinfo.email'
      ]
    }), users.signin);
  app.get('/auth/google/callback',
    passport.authenticate('google', {
      failureRedirect: '/login'
    }), users.authCallback);
  app.get('/auth/linkedin',
    passport.authenticate('linkedin', {
      failureRedirect: '/login',
      scope: [
        'r_emailaddress'
      ]
    }), users.signin);
  app.get('/auth/linkedin/callback',
    passport.authenticate('linkedin', {
      failureRedirect: '/login'
    }), users.authCallback);

  app.param('userId', users.load);

  app.get('/users', users.list);



 app.param('userId1', users.loadOther);
var userComments = require('../app/controllers/userComments.js');
 app.param('userCommentId', userComments.load);
app.post('/user/:userId1/comments', auth.requiresLogin, userComments.create);
app.get('/user/:userId1/comments', auth.requiresLogin, userComments.create);
app.delete('/user/:userId1/comments/:userCommentId', userComments.destroy);
 

var userRatings = require('../app/controllers/userRatings.js');
 app.param('userRatingId', userRatings.load);
app.post('/user/:userId1/ratings', auth.requiresLogin, userRatings.create);
app.get('/user/:userId1/ratings', auth.requiresLogin, userRatings.create);
app.delete('/user/:userId1/ratings/:userRatingId', userRatings.destroy);
 

var userLikes = require('../app/controllers/userLikes.js');
 app.param('userLikeId', userLikes.load);
app.post('/user/:userId1/likes', auth.requiresLogin, userLikes.create);
app.get('/user/:userId1/likes', auth.requiresLogin, userLikes.create);
app.delete('/user/:userId1/likes/:userLikeId', userLikes.destroy);
 

var userCategories = require('../app/controllers/userCategories.js');
 app.param('userCategoryId', userCategories.load);
app.post('/user/:userId1/categories', auth.requiresLogin, userCategories.create);
app.get('/user/:userId1/categories', auth.requiresLogin, userCategories.create);
app.delete('/user/:userId1/categories/:userCategoryId', userCategories.destroy);
 


 var userFollowing= require('../app/controllers/userFollowing.js');
 app.param('userFollowingId', userLikes.load);
app.post('/user/:userId1/following', auth.requiresLogin, userFollowing.create);
app.get('/user/:userId1/following', auth.requiresLogin, userFollowing.create);
app.delete('/user/:userId1/follwoing/:userFollowingId', userFollowing.destroy);
 






var userComments = require('../app/controllers/userComments.js');
 app.param('userCommentId', userComments.load);
app.post('/users/:userId1/comments', auth.requiresLogin, userComments.create);
app.get('/users/:userId1/comments', auth.requiresLogin, userComments.create);
app.delete('/users/:userId1/comments/:userCommentId', userComments.destroy);
 

var userRatings = require('../app/controllers/userRatings.js');
 app.param('userRatingId', userRatings.load);
app.post('/users/:userId1/ratings', auth.requiresLogin, userRatings.create);
app.get('/users/:userId1/ratings', auth.requiresLogin, userRatings.create);
app.delete('/users/:userId1/ratings/:userRatingId', userRatings.destroy);
 

var userLikes = require('../app/controllers/userLikes.js');
 app.param('userLikeId', userLikes.load);
app.post('/users/:userId1/likes', auth.requiresLogin, userLikes.create);
app.get('/users/:userId1/likes', auth.requiresLogin, userLikes.create);
app.delete('/users/:userId1/likes/:userLikeId', userLikes.destroy);
 

var userCategories = require('../app/controllers/userCategories.js');
 app.param('userCategoryId', userCategories.load);
app.post('/users/:userId1/categories', auth.requiresLogin, userCategories.create);
app.get('/users/:userId1/categories', auth.requiresLogin, userCategories.create);
app.delete('/users/:userId1/categories/:userCategoryId', userCategories.destroy);
 


 var userFollowing= require('../app/controllers/userFollowing.js');
 app.param('userFollowingId', userLikes.load);
app.post('/users/:userId1/following', auth.requiresLogin, userFollowing.create);
app.get('/users/:userId1/following', auth.requiresLogin, userFollowing.create);
app.delete('/users/:userId1/follwoing/:userFollowingId', userFollowing.destroy);
 





  // article routes
  app.param('id', articles.load);
  app.get('/articles', articles.index);
  app.get('/articles/new', auth.requiresLogin, articles.new);
  app.post('/articles', auth.requiresLogin, articles.create);
  app.get('/articles/:id', articles.show);
  app.get('/articles/:id/edit', articleAuth, articles.edit);
  app.put('/articles/:id', articleAuth, articles.update);
  app.delete('/articles/:id', articleAuth, articles.destroy);

  app.param('messageId', messages.load);
  app.get('/messages', messages.index);
  app.get('/messages/myMessages', messages.myMessages);
  app.get('/messages/conversations', messages.conversations);
  app.get('/messages/new', auth.requiresLogin, messages.new);
  app.post('/messages', auth.requiresLogin, messages.create);
  app.get('/messages/:messageId', messages.show);
  app.get('/messages/:messageId/edit', messages.edit);
  app.put('/messages/:messageId', messages.update);
  app.delete('/messages/:messageId', messages.destroy);

  // home route
  app.get('/', articles.index);
  app.get('/beta', welcome.index);

  try{

  //generator-- 
  app.get('/generateViews', generator.generateNavigation);
  app.get('/return', generator.returnBack);
  app.get('/sampleGen', generator.sampleGen);
  app.get('/generateApp', generator.generateApp);
    app.get('/generateSample', generator.generateSample);



  app.get('/generateMobile', mobileGenerator.generateMobile);
   app.get('/returnMobile', mobileGenerator.returnM);

  //end generator--

  }

  catch(err){
    console.log('\n\n--CodeSwatch');
  }
//generated routes 
	 app.param('learnMoreId', learnMore.load); 

app.get('/learnMore', learnMore.index); 
 app.get('/learnMore/new', auth.requiresLogin, learnMore.new); 
 app.get('/learnMore/list', learnMore.list); 
   app.post('/learnMore', auth.requiresLogin, learnMore.create);
 app.get('/learnMore/:learnMoreId', learnMore.show);
 app.get('/learnMore/:learnMoreId/edit', learnMore.edit);
 app.put('/learnMore/:learnMoreId', learnMore.update);
  app.delete('/learnMore/:learnMoreId', learnMore.destroy);

app.param('learnMoreId', learnMore.load); 

 app.get('/learnMores', learnMore.index); 
 app.get('/learnMores/new', auth.requiresLogin, learnMore.new); 
 app.get('/learnMores/list', learnMore.list); 
   app.post('/learnMores', auth.requiresLogin, learnMore.create);
 app.get('/learnMores/:learnMoreId', learnMore.show);
 app.get('/learnMores/:learnMoreId/edit', learnMore.edit);
 app.put('/learnMores/:learnMoreId', learnMore.update);
  app.delete('/learnMores/:learnMoreId', learnMore.destroy);


 

var learnMoreComments = require('../app/genControllers/learnMoreComments.js');
 app.param('learnMoreCommentId', learnMoreComments.load);
app.post('/learnMore/:learnMoreId/comments', auth.requiresLogin, learnMoreComments.create);
app.get('/learnMore/:learnMoreId/comments', auth.requiresLogin, learnMoreComments.create);
app.delete('/learnMore/:learnMoreId/comments/:learnMoreCommentId', learnMoreComments.destroy);
 

var learnMoreComments = require('../app/genControllers/learnMoreComments.js');
 app.param('learnMoreCommentId', learnMoreComments.load);
app.post('/learnMores/:learnMoreId/comments', auth.requiresLogin, learnMoreComments.create);
app.get('/learnMores/:learnMoreId/comments', auth.requiresLogin, learnMoreComments.create);
app.delete('/learnMores/:learnMoreId/comments/:learnMoreCommentId', learnMoreComments.destroy);
 

var learnMoreRatings = require('../app/genControllers/learnMoreRatings.js');
 app.param('learnMoreRatingId', learnMoreRatings.load);
app.post('/learnMore/:learnMoreId/ratings', auth.requiresLogin, learnMoreRatings.create);
app.get('/learnMore/:learnMoreId/ratings', auth.requiresLogin, learnMoreRatings.create);
app.delete('/learnMore/:learnMoreId/ratings/:learnMoreRatingId', learnMoreRatings.destroy);
 

var learnMoreRatings = require('../app/genControllers/learnMoreRatings.js');
 app.param('learnMoreRatingId', learnMoreRatings.load);
app.post('/learnMores/:learnMoreId/ratings', auth.requiresLogin, learnMoreRatings.create);
app.get('/learnMores/:learnMoreId/ratings', auth.requiresLogin, learnMoreRatings.create);
app.delete('/learnMores/:learnMoreId/ratings/:learnMoreRatingId', learnMoreRatings.destroy);
 

var learnMoreLikes = require('../app/genControllers/learnMoreLikes.js');
 app.param('learnMoreLikeId', learnMoreLikes.load);
app.post('/learnMore/:learnMoreId/likes', auth.requiresLogin, learnMoreLikes.create);
app.get('/learnMore/:learnMoreId/likes', auth.requiresLogin, learnMoreLikes.create);
app.delete('/learnMore/:learnMoreId/likes/:learnMoreLikeId', learnMoreLikes.destroy);
 

var learnMoreLikes = require('../app/genControllers/learnMoreLikes.js');
 app.param('learnMoreLikeId', learnMoreLikes.load);
app.post('/learnMores/:learnMoreId/likes', auth.requiresLogin, learnMoreLikes.create);
app.get('/learnMores/:learnMoreId/likes', auth.requiresLogin, learnMoreLikes.create);
app.delete('/learnMores/:learnMoreId/likes/:learnMoreLikeId', learnMoreLikes.destroy);
 

var learnMoreCategories = require('../app/genControllers/learnMoreCategories.js');
 app.param('learnMoreCategoryId', learnMoreCategories.load);
app.post('/learnMore/:learnMoreId/categories', auth.requiresLogin, learnMoreCategories.create);
app.get('/learnMore/:learnMoreId/categories', auth.requiresLogin, learnMoreCategories.create);
app.delete('/learnMore/:learnMoreId/categories/:learnMoreCategoryId', learnMoreCategories.destroy);
 

var learnMoreCategories = require('../app/genControllers/learnMoreCategories.js');
 app.param('learnMoreCategoryId', learnMoreCategories.load);
app.post('/learnMores/:learnMoreId/categories', auth.requiresLogin, learnMoreCategories.create);
app.get('/learnMores/:learnMoreId/categories', auth.requiresLogin, learnMoreCategories.create);
app.delete('/learnMores/:learnMoreId/categories/:learnMoreCategoryId', learnMoreCategories.destroy);
	 
	 app.param('recentlySearchedId', recentlySearched.load); 

app.get('/recentlySearched', recentlySearched.index); 
 app.get('/recentlySearched/new', auth.requiresLogin, recentlySearched.new); 
 app.get('/recentlySearched/list', recentlySearched.list); 
   app.post('/recentlySearched', auth.requiresLogin, recentlySearched.create);
 app.get('/recentlySearched/:recentlySearchedId', recentlySearched.show);
 app.get('/recentlySearched/:recentlySearchedId/edit', recentlySearched.edit);
 app.put('/recentlySearched/:recentlySearchedId', recentlySearched.update);
  app.delete('/recentlySearched/:recentlySearchedId', recentlySearched.destroy);

app.param('recentlySearchedId', recentlySearched.load); 

 app.get('/recentlySearcheds', recentlySearched.index); 
 app.get('/recentlySearcheds/new', auth.requiresLogin, recentlySearched.new); 
 app.get('/recentlySearcheds/list', recentlySearched.list); 
   app.post('/recentlySearcheds', auth.requiresLogin, recentlySearched.create);
 app.get('/recentlySearcheds/:recentlySearchedId', recentlySearched.show);
 app.get('/recentlySearcheds/:recentlySearchedId/edit', recentlySearched.edit);
 app.put('/recentlySearcheds/:recentlySearchedId', recentlySearched.update);
  app.delete('/recentlySearcheds/:recentlySearchedId', recentlySearched.destroy);


 

var recentlySearchedComments = require('../app/genControllers/recentlySearchedComments.js');
 app.param('recentlySearchedCommentId', recentlySearchedComments.load);
app.post('/recentlySearched/:recentlySearchedId/comments', auth.requiresLogin, recentlySearchedComments.create);
app.get('/recentlySearched/:recentlySearchedId/comments', auth.requiresLogin, recentlySearchedComments.create);
app.delete('/recentlySearched/:recentlySearchedId/comments/:recentlySearchedCommentId', recentlySearchedComments.destroy);
 

var recentlySearchedComments = require('../app/genControllers/recentlySearchedComments.js');
 app.param('recentlySearchedCommentId', recentlySearchedComments.load);
app.post('/recentlySearcheds/:recentlySearchedId/comments', auth.requiresLogin, recentlySearchedComments.create);
app.get('/recentlySearcheds/:recentlySearchedId/comments', auth.requiresLogin, recentlySearchedComments.create);
app.delete('/recentlySearcheds/:recentlySearchedId/comments/:recentlySearchedCommentId', recentlySearchedComments.destroy);
 

var recentlySearchedRatings = require('../app/genControllers/recentlySearchedRatings.js');
 app.param('recentlySearchedRatingId', recentlySearchedRatings.load);
app.post('/recentlySearched/:recentlySearchedId/ratings', auth.requiresLogin, recentlySearchedRatings.create);
app.get('/recentlySearched/:recentlySearchedId/ratings', auth.requiresLogin, recentlySearchedRatings.create);
app.delete('/recentlySearched/:recentlySearchedId/ratings/:recentlySearchedRatingId', recentlySearchedRatings.destroy);
 

var recentlySearchedRatings = require('../app/genControllers/recentlySearchedRatings.js');
 app.param('recentlySearchedRatingId', recentlySearchedRatings.load);
app.post('/recentlySearcheds/:recentlySearchedId/ratings', auth.requiresLogin, recentlySearchedRatings.create);
app.get('/recentlySearcheds/:recentlySearchedId/ratings', auth.requiresLogin, recentlySearchedRatings.create);
app.delete('/recentlySearcheds/:recentlySearchedId/ratings/:recentlySearchedRatingId', recentlySearchedRatings.destroy);
 

var recentlySearchedLikes = require('../app/genControllers/recentlySearchedLikes.js');
 app.param('recentlySearchedLikeId', recentlySearchedLikes.load);
app.post('/recentlySearched/:recentlySearchedId/likes', auth.requiresLogin, recentlySearchedLikes.create);
app.get('/recentlySearched/:recentlySearchedId/likes', auth.requiresLogin, recentlySearchedLikes.create);
app.delete('/recentlySearched/:recentlySearchedId/likes/:recentlySearchedLikeId', recentlySearchedLikes.destroy);
 

var recentlySearchedLikes = require('../app/genControllers/recentlySearchedLikes.js');
 app.param('recentlySearchedLikeId', recentlySearchedLikes.load);
app.post('/recentlySearcheds/:recentlySearchedId/likes', auth.requiresLogin, recentlySearchedLikes.create);
app.get('/recentlySearcheds/:recentlySearchedId/likes', auth.requiresLogin, recentlySearchedLikes.create);
app.delete('/recentlySearcheds/:recentlySearchedId/likes/:recentlySearchedLikeId', recentlySearchedLikes.destroy);
 

var recentlySearchedCategories = require('../app/genControllers/recentlySearchedCategories.js');
 app.param('recentlySearchedCategoryId', recentlySearchedCategories.load);
app.post('/recentlySearched/:recentlySearchedId/categories', auth.requiresLogin, recentlySearchedCategories.create);
app.get('/recentlySearched/:recentlySearchedId/categories', auth.requiresLogin, recentlySearchedCategories.create);
app.delete('/recentlySearched/:recentlySearchedId/categories/:recentlySearchedCategoryId', recentlySearchedCategories.destroy);
 

var recentlySearchedCategories = require('../app/genControllers/recentlySearchedCategories.js');
 app.param('recentlySearchedCategoryId', recentlySearchedCategories.load);
app.post('/recentlySearcheds/:recentlySearchedId/categories', auth.requiresLogin, recentlySearchedCategories.create);
app.get('/recentlySearcheds/:recentlySearchedId/categories', auth.requiresLogin, recentlySearchedCategories.create);
app.delete('/recentlySearcheds/:recentlySearchedId/categories/:recentlySearchedCategoryId', recentlySearchedCategories.destroy);
	 
	 app.param('resultId', result.load); 

app.get('/result', result.index); 
 app.get('/result/new', auth.requiresLogin, result.new); 
 app.get('/result/list', result.list); 
   app.post('/result', auth.requiresLogin, result.create);
 app.get('/result/:resultId', result.show);
 app.get('/result/:resultId/edit', result.edit);
 app.put('/result/:resultId', result.update);
  app.delete('/result/:resultId', result.destroy);

app.param('resultId', result.load); 

 app.get('/results', result.index); 
 app.get('/results/new', auth.requiresLogin, result.new); 
 app.get('/results/list', result.list); 
   app.post('/results', auth.requiresLogin, result.create);
 app.get('/results/:resultId', result.show);
 app.get('/results/:resultId/edit', result.edit);
 app.put('/results/:resultId', result.update);
  app.delete('/results/:resultId', result.destroy);


 

var resultComments = require('../app/genControllers/resultComments.js');
 app.param('resultCommentId', resultComments.load);
app.post('/result/:resultId/comments', auth.requiresLogin, resultComments.create);
app.get('/result/:resultId/comments', auth.requiresLogin, resultComments.create);
app.delete('/result/:resultId/comments/:resultCommentId', resultComments.destroy);
 

var resultComments = require('../app/genControllers/resultComments.js');
 app.param('resultCommentId', resultComments.load);
app.post('/results/:resultId/comments', auth.requiresLogin, resultComments.create);
app.get('/results/:resultId/comments', auth.requiresLogin, resultComments.create);
app.delete('/results/:resultId/comments/:resultCommentId', resultComments.destroy);
 

var resultRatings = require('../app/genControllers/resultRatings.js');
 app.param('resultRatingId', resultRatings.load);
app.post('/result/:resultId/ratings', auth.requiresLogin, resultRatings.create);
app.get('/result/:resultId/ratings', auth.requiresLogin, resultRatings.create);
app.delete('/result/:resultId/ratings/:resultRatingId', resultRatings.destroy);
 

var resultRatings = require('../app/genControllers/resultRatings.js');
 app.param('resultRatingId', resultRatings.load);
app.post('/results/:resultId/ratings', auth.requiresLogin, resultRatings.create);
app.get('/results/:resultId/ratings', auth.requiresLogin, resultRatings.create);
app.delete('/results/:resultId/ratings/:resultRatingId', resultRatings.destroy);
 

var resultLikes = require('../app/genControllers/resultLikes.js');
 app.param('resultLikeId', resultLikes.load);
app.post('/result/:resultId/likes', auth.requiresLogin, resultLikes.create);
app.get('/result/:resultId/likes', auth.requiresLogin, resultLikes.create);
app.delete('/result/:resultId/likes/:resultLikeId', resultLikes.destroy);
 

var resultLikes = require('../app/genControllers/resultLikes.js');
 app.param('resultLikeId', resultLikes.load);
app.post('/results/:resultId/likes', auth.requiresLogin, resultLikes.create);
app.get('/results/:resultId/likes', auth.requiresLogin, resultLikes.create);
app.delete('/results/:resultId/likes/:resultLikeId', resultLikes.destroy);
 

var resultCategories = require('../app/genControllers/resultCategories.js');
 app.param('resultCategoryId', resultCategories.load);
app.post('/result/:resultId/categories', auth.requiresLogin, resultCategories.create);
app.get('/result/:resultId/categories', auth.requiresLogin, resultCategories.create);
app.delete('/result/:resultId/categories/:resultCategoryId', resultCategories.destroy);
 

var resultCategories = require('../app/genControllers/resultCategories.js');
 app.param('resultCategoryId', resultCategories.load);
app.post('/results/:resultId/categories', auth.requiresLogin, resultCategories.create);
app.get('/results/:resultId/categories', auth.requiresLogin, resultCategories.create);
app.delete('/results/:resultId/categories/:resultCategoryId', resultCategories.destroy);
	 
	 app.param('searchId', search.load); 

app.get('/search', search.index); 
 app.get('/search/new', auth.requiresLogin, search.new); 
 app.get('/search/list', search.list); 
   app.post('/search', auth.requiresLogin, search.create);
 app.get('/search/:searchId', search.show);
 app.get('/search/:searchId/edit', search.edit);
 app.put('/search/:searchId', search.update);
  app.delete('/search/:searchId', search.destroy);

app.param('searchId', search.load); 

 app.get('/searchs', search.index); 
 app.get('/searchs/new', auth.requiresLogin, search.new); 
 app.get('/searchs/list', search.list); 
   app.post('/searchs', auth.requiresLogin, search.create);
 app.get('/searchs/:searchId', search.show);
 app.get('/searchs/:searchId/edit', search.edit);
 app.put('/searchs/:searchId', search.update);
  app.delete('/searchs/:searchId', search.destroy);


 

var searchComments = require('../app/genControllers/searchComments.js');
 app.param('searchCommentId', searchComments.load);
app.post('/search/:searchId/comments', auth.requiresLogin, searchComments.create);
app.get('/search/:searchId/comments', auth.requiresLogin, searchComments.create);
app.delete('/search/:searchId/comments/:searchCommentId', searchComments.destroy);
 

var searchComments = require('../app/genControllers/searchComments.js');
 app.param('searchCommentId', searchComments.load);
app.post('/searchs/:searchId/comments', auth.requiresLogin, searchComments.create);
app.get('/searchs/:searchId/comments', auth.requiresLogin, searchComments.create);
app.delete('/searchs/:searchId/comments/:searchCommentId', searchComments.destroy);
 

var searchRatings = require('../app/genControllers/searchRatings.js');
 app.param('searchRatingId', searchRatings.load);
app.post('/search/:searchId/ratings', auth.requiresLogin, searchRatings.create);
app.get('/search/:searchId/ratings', auth.requiresLogin, searchRatings.create);
app.delete('/search/:searchId/ratings/:searchRatingId', searchRatings.destroy);
 

var searchRatings = require('../app/genControllers/searchRatings.js');
 app.param('searchRatingId', searchRatings.load);
app.post('/searchs/:searchId/ratings', auth.requiresLogin, searchRatings.create);
app.get('/searchs/:searchId/ratings', auth.requiresLogin, searchRatings.create);
app.delete('/searchs/:searchId/ratings/:searchRatingId', searchRatings.destroy);
 

var searchLikes = require('../app/genControllers/searchLikes.js');
 app.param('searchLikeId', searchLikes.load);
app.post('/search/:searchId/likes', auth.requiresLogin, searchLikes.create);
app.get('/search/:searchId/likes', auth.requiresLogin, searchLikes.create);
app.delete('/search/:searchId/likes/:searchLikeId', searchLikes.destroy);
 

var searchLikes = require('../app/genControllers/searchLikes.js');
 app.param('searchLikeId', searchLikes.load);
app.post('/searchs/:searchId/likes', auth.requiresLogin, searchLikes.create);
app.get('/searchs/:searchId/likes', auth.requiresLogin, searchLikes.create);
app.delete('/searchs/:searchId/likes/:searchLikeId', searchLikes.destroy);
 

var searchCategories = require('../app/genControllers/searchCategories.js');
 app.param('searchCategoryId', searchCategories.load);
app.post('/search/:searchId/categories', auth.requiresLogin, searchCategories.create);
app.get('/search/:searchId/categories', auth.requiresLogin, searchCategories.create);
app.delete('/search/:searchId/categories/:searchCategoryId', searchCategories.destroy);
 

var searchCategories = require('../app/genControllers/searchCategories.js');
 app.param('searchCategoryId', searchCategories.load);
app.post('/searchs/:searchId/categories', auth.requiresLogin, searchCategories.create);
app.get('/searchs/:searchId/categories', auth.requiresLogin, searchCategories.create);
app.delete('/searchs/:searchId/categories/:searchCategoryId', searchCategories.destroy);
	 
	 app.param('detailId', detail.load); 

app.get('/detail', detail.index); 
 app.get('/detail/new', auth.requiresLogin, detail.new); 
 app.get('/detail/list', detail.list); 
   app.post('/detail', auth.requiresLogin, detail.create);
 app.get('/detail/:detailId', detail.show);
 app.get('/detail/:detailId/edit', detail.edit);
 app.put('/detail/:detailId', detail.update);
  app.delete('/detail/:detailId', detail.destroy);

app.param('detailId', detail.load); 

 app.get('/details', detail.index); 
 app.get('/details/new', auth.requiresLogin, detail.new); 
 app.get('/details/list', detail.list); 
   app.post('/details', auth.requiresLogin, detail.create);
 app.get('/details/:detailId', detail.show);
 app.get('/details/:detailId/edit', detail.edit);
 app.put('/details/:detailId', detail.update);
  app.delete('/details/:detailId', detail.destroy);


 

var detailComments = require('../app/genControllers/detailComments.js');
 app.param('detailCommentId', detailComments.load);
app.post('/detail/:detailId/comments', auth.requiresLogin, detailComments.create);
app.get('/detail/:detailId/comments', auth.requiresLogin, detailComments.create);
app.delete('/detail/:detailId/comments/:detailCommentId', detailComments.destroy);
 

var detailComments = require('../app/genControllers/detailComments.js');
 app.param('detailCommentId', detailComments.load);
app.post('/details/:detailId/comments', auth.requiresLogin, detailComments.create);
app.get('/details/:detailId/comments', auth.requiresLogin, detailComments.create);
app.delete('/details/:detailId/comments/:detailCommentId', detailComments.destroy);
 

var detailRatings = require('../app/genControllers/detailRatings.js');
 app.param('detailRatingId', detailRatings.load);
app.post('/detail/:detailId/ratings', auth.requiresLogin, detailRatings.create);
app.get('/detail/:detailId/ratings', auth.requiresLogin, detailRatings.create);
app.delete('/detail/:detailId/ratings/:detailRatingId', detailRatings.destroy);
 

var detailRatings = require('../app/genControllers/detailRatings.js');
 app.param('detailRatingId', detailRatings.load);
app.post('/details/:detailId/ratings', auth.requiresLogin, detailRatings.create);
app.get('/details/:detailId/ratings', auth.requiresLogin, detailRatings.create);
app.delete('/details/:detailId/ratings/:detailRatingId', detailRatings.destroy);
 

var detailLikes = require('../app/genControllers/detailLikes.js');
 app.param('detailLikeId', detailLikes.load);
app.post('/detail/:detailId/likes', auth.requiresLogin, detailLikes.create);
app.get('/detail/:detailId/likes', auth.requiresLogin, detailLikes.create);
app.delete('/detail/:detailId/likes/:detailLikeId', detailLikes.destroy);
 

var detailLikes = require('../app/genControllers/detailLikes.js');
 app.param('detailLikeId', detailLikes.load);
app.post('/details/:detailId/likes', auth.requiresLogin, detailLikes.create);
app.get('/details/:detailId/likes', auth.requiresLogin, detailLikes.create);
app.delete('/details/:detailId/likes/:detailLikeId', detailLikes.destroy);
 

var detailCategories = require('../app/genControllers/detailCategories.js');
 app.param('detailCategoryId', detailCategories.load);
app.post('/detail/:detailId/categories', auth.requiresLogin, detailCategories.create);
app.get('/detail/:detailId/categories', auth.requiresLogin, detailCategories.create);
app.delete('/detail/:detailId/categories/:detailCategoryId', detailCategories.destroy);
 

var detailCategories = require('../app/genControllers/detailCategories.js');
 app.param('detailCategoryId', detailCategories.load);
app.post('/details/:detailId/categories', auth.requiresLogin, detailCategories.create);
app.get('/details/:detailId/categories', auth.requiresLogin, detailCategories.create);
app.delete('/details/:detailId/categories/:detailCategoryId', detailCategories.destroy);
	 
	 app.param('recentlyViewedId', recentlyViewed.load); 

app.get('/recentlyViewed', recentlyViewed.index); 
 app.get('/recentlyViewed/new', auth.requiresLogin, recentlyViewed.new); 
 app.get('/recentlyViewed/list', recentlyViewed.list); 
   app.post('/recentlyViewed', auth.requiresLogin, recentlyViewed.create);
 app.get('/recentlyViewed/:recentlyViewedId', recentlyViewed.show);
 app.get('/recentlyViewed/:recentlyViewedId/edit', recentlyViewed.edit);
 app.put('/recentlyViewed/:recentlyViewedId', recentlyViewed.update);
  app.delete('/recentlyViewed/:recentlyViewedId', recentlyViewed.destroy);

app.param('recentlyViewedId', recentlyViewed.load); 

 app.get('/recentlyVieweds', recentlyViewed.index); 
 app.get('/recentlyVieweds/new', auth.requiresLogin, recentlyViewed.new); 
 app.get('/recentlyVieweds/list', recentlyViewed.list); 
   app.post('/recentlyVieweds', auth.requiresLogin, recentlyViewed.create);
 app.get('/recentlyVieweds/:recentlyViewedId', recentlyViewed.show);
 app.get('/recentlyVieweds/:recentlyViewedId/edit', recentlyViewed.edit);
 app.put('/recentlyVieweds/:recentlyViewedId', recentlyViewed.update);
  app.delete('/recentlyVieweds/:recentlyViewedId', recentlyViewed.destroy);


 

var recentlyViewedComments = require('../app/genControllers/recentlyViewedComments.js');
 app.param('recentlyViewedCommentId', recentlyViewedComments.load);
app.post('/recentlyViewed/:recentlyViewedId/comments', auth.requiresLogin, recentlyViewedComments.create);
app.get('/recentlyViewed/:recentlyViewedId/comments', auth.requiresLogin, recentlyViewedComments.create);
app.delete('/recentlyViewed/:recentlyViewedId/comments/:recentlyViewedCommentId', recentlyViewedComments.destroy);
 

var recentlyViewedComments = require('../app/genControllers/recentlyViewedComments.js');
 app.param('recentlyViewedCommentId', recentlyViewedComments.load);
app.post('/recentlyVieweds/:recentlyViewedId/comments', auth.requiresLogin, recentlyViewedComments.create);
app.get('/recentlyVieweds/:recentlyViewedId/comments', auth.requiresLogin, recentlyViewedComments.create);
app.delete('/recentlyVieweds/:recentlyViewedId/comments/:recentlyViewedCommentId', recentlyViewedComments.destroy);
 

var recentlyViewedRatings = require('../app/genControllers/recentlyViewedRatings.js');
 app.param('recentlyViewedRatingId', recentlyViewedRatings.load);
app.post('/recentlyViewed/:recentlyViewedId/ratings', auth.requiresLogin, recentlyViewedRatings.create);
app.get('/recentlyViewed/:recentlyViewedId/ratings', auth.requiresLogin, recentlyViewedRatings.create);
app.delete('/recentlyViewed/:recentlyViewedId/ratings/:recentlyViewedRatingId', recentlyViewedRatings.destroy);
 

var recentlyViewedRatings = require('../app/genControllers/recentlyViewedRatings.js');
 app.param('recentlyViewedRatingId', recentlyViewedRatings.load);
app.post('/recentlyVieweds/:recentlyViewedId/ratings', auth.requiresLogin, recentlyViewedRatings.create);
app.get('/recentlyVieweds/:recentlyViewedId/ratings', auth.requiresLogin, recentlyViewedRatings.create);
app.delete('/recentlyVieweds/:recentlyViewedId/ratings/:recentlyViewedRatingId', recentlyViewedRatings.destroy);
 

var recentlyViewedLikes = require('../app/genControllers/recentlyViewedLikes.js');
 app.param('recentlyViewedLikeId', recentlyViewedLikes.load);
app.post('/recentlyViewed/:recentlyViewedId/likes', auth.requiresLogin, recentlyViewedLikes.create);
app.get('/recentlyViewed/:recentlyViewedId/likes', auth.requiresLogin, recentlyViewedLikes.create);
app.delete('/recentlyViewed/:recentlyViewedId/likes/:recentlyViewedLikeId', recentlyViewedLikes.destroy);
 

var recentlyViewedLikes = require('../app/genControllers/recentlyViewedLikes.js');
 app.param('recentlyViewedLikeId', recentlyViewedLikes.load);
app.post('/recentlyVieweds/:recentlyViewedId/likes', auth.requiresLogin, recentlyViewedLikes.create);
app.get('/recentlyVieweds/:recentlyViewedId/likes', auth.requiresLogin, recentlyViewedLikes.create);
app.delete('/recentlyVieweds/:recentlyViewedId/likes/:recentlyViewedLikeId', recentlyViewedLikes.destroy);
 

var recentlyViewedCategories = require('../app/genControllers/recentlyViewedCategories.js');
 app.param('recentlyViewedCategoryId', recentlyViewedCategories.load);
app.post('/recentlyViewed/:recentlyViewedId/categories', auth.requiresLogin, recentlyViewedCategories.create);
app.get('/recentlyViewed/:recentlyViewedId/categories', auth.requiresLogin, recentlyViewedCategories.create);
app.delete('/recentlyViewed/:recentlyViewedId/categories/:recentlyViewedCategoryId', recentlyViewedCategories.destroy);
 

var recentlyViewedCategories = require('../app/genControllers/recentlyViewedCategories.js');
 app.param('recentlyViewedCategoryId', recentlyViewedCategories.load);
app.post('/recentlyVieweds/:recentlyViewedId/categories', auth.requiresLogin, recentlyViewedCategories.create);
app.get('/recentlyVieweds/:recentlyViewedId/categories', auth.requiresLogin, recentlyViewedCategories.create);
app.delete('/recentlyVieweds/:recentlyViewedId/categories/:recentlyViewedCategoryId', recentlyViewedCategories.destroy);
	 
	 app.param('myAccountId', myAccount.load); 

app.get('/myAccount', myAccount.index); 
 app.get('/myAccount/new', auth.requiresLogin, myAccount.new); 
 app.get('/myAccount/list', myAccount.list); 
   app.post('/myAccount', auth.requiresLogin, myAccount.create);
 app.get('/myAccount/:myAccountId', myAccount.show);
 app.get('/myAccount/:myAccountId/edit', myAccount.edit);
 app.put('/myAccount/:myAccountId', myAccount.update);
  app.delete('/myAccount/:myAccountId', myAccount.destroy);

app.param('myAccountId', myAccount.load); 

 app.get('/myAccounts', myAccount.index); 
 app.get('/myAccounts/new', auth.requiresLogin, myAccount.new); 
 app.get('/myAccounts/list', myAccount.list); 
   app.post('/myAccounts', auth.requiresLogin, myAccount.create);
 app.get('/myAccounts/:myAccountId', myAccount.show);
 app.get('/myAccounts/:myAccountId/edit', myAccount.edit);
 app.put('/myAccounts/:myAccountId', myAccount.update);
  app.delete('/myAccounts/:myAccountId', myAccount.destroy);


 

var myAccountComments = require('../app/genControllers/myAccountComments.js');
 app.param('myAccountCommentId', myAccountComments.load);
app.post('/myAccount/:myAccountId/comments', auth.requiresLogin, myAccountComments.create);
app.get('/myAccount/:myAccountId/comments', auth.requiresLogin, myAccountComments.create);
app.delete('/myAccount/:myAccountId/comments/:myAccountCommentId', myAccountComments.destroy);
 

var myAccountComments = require('../app/genControllers/myAccountComments.js');
 app.param('myAccountCommentId', myAccountComments.load);
app.post('/myAccounts/:myAccountId/comments', auth.requiresLogin, myAccountComments.create);
app.get('/myAccounts/:myAccountId/comments', auth.requiresLogin, myAccountComments.create);
app.delete('/myAccounts/:myAccountId/comments/:myAccountCommentId', myAccountComments.destroy);
 

var myAccountRatings = require('../app/genControllers/myAccountRatings.js');
 app.param('myAccountRatingId', myAccountRatings.load);
app.post('/myAccount/:myAccountId/ratings', auth.requiresLogin, myAccountRatings.create);
app.get('/myAccount/:myAccountId/ratings', auth.requiresLogin, myAccountRatings.create);
app.delete('/myAccount/:myAccountId/ratings/:myAccountRatingId', myAccountRatings.destroy);
 

var myAccountRatings = require('../app/genControllers/myAccountRatings.js');
 app.param('myAccountRatingId', myAccountRatings.load);
app.post('/myAccounts/:myAccountId/ratings', auth.requiresLogin, myAccountRatings.create);
app.get('/myAccounts/:myAccountId/ratings', auth.requiresLogin, myAccountRatings.create);
app.delete('/myAccounts/:myAccountId/ratings/:myAccountRatingId', myAccountRatings.destroy);
 

var myAccountLikes = require('../app/genControllers/myAccountLikes.js');
 app.param('myAccountLikeId', myAccountLikes.load);
app.post('/myAccount/:myAccountId/likes', auth.requiresLogin, myAccountLikes.create);
app.get('/myAccount/:myAccountId/likes', auth.requiresLogin, myAccountLikes.create);
app.delete('/myAccount/:myAccountId/likes/:myAccountLikeId', myAccountLikes.destroy);
 

var myAccountLikes = require('../app/genControllers/myAccountLikes.js');
 app.param('myAccountLikeId', myAccountLikes.load);
app.post('/myAccounts/:myAccountId/likes', auth.requiresLogin, myAccountLikes.create);
app.get('/myAccounts/:myAccountId/likes', auth.requiresLogin, myAccountLikes.create);
app.delete('/myAccounts/:myAccountId/likes/:myAccountLikeId', myAccountLikes.destroy);
 

var myAccountCategories = require('../app/genControllers/myAccountCategories.js');
 app.param('myAccountCategoryId', myAccountCategories.load);
app.post('/myAccount/:myAccountId/categories', auth.requiresLogin, myAccountCategories.create);
app.get('/myAccount/:myAccountId/categories', auth.requiresLogin, myAccountCategories.create);
app.delete('/myAccount/:myAccountId/categories/:myAccountCategoryId', myAccountCategories.destroy);
 

var myAccountCategories = require('../app/genControllers/myAccountCategories.js');
 app.param('myAccountCategoryId', myAccountCategories.load);
app.post('/myAccounts/:myAccountId/categories', auth.requiresLogin, myAccountCategories.create);
app.get('/myAccounts/:myAccountId/categories', auth.requiresLogin, myAccountCategories.create);
app.delete('/myAccounts/:myAccountId/categories/:myAccountCategoryId', myAccountCategories.destroy);
	 
	 app.param('browseId', browse.load); 

app.get('/browse', browse.index); 
 app.get('/browse/new', auth.requiresLogin, browse.new); 
 app.get('/browse/list', browse.list); 
   app.post('/browse', auth.requiresLogin, browse.create);
 app.get('/browse/:browseId', browse.show);
 app.get('/browse/:browseId/edit', browse.edit);
 app.put('/browse/:browseId', browse.update);
  app.delete('/browse/:browseId', browse.destroy);

app.param('browseId', browse.load); 

 app.get('/browses', browse.index); 
 app.get('/browses/new', auth.requiresLogin, browse.new); 
 app.get('/browses/list', browse.list); 
   app.post('/browses', auth.requiresLogin, browse.create);
 app.get('/browses/:browseId', browse.show);
 app.get('/browses/:browseId/edit', browse.edit);
 app.put('/browses/:browseId', browse.update);
  app.delete('/browses/:browseId', browse.destroy);


 

var browseComments = require('../app/genControllers/browseComments.js');
 app.param('browseCommentId', browseComments.load);
app.post('/browse/:browseId/comments', auth.requiresLogin, browseComments.create);
app.get('/browse/:browseId/comments', auth.requiresLogin, browseComments.create);
app.delete('/browse/:browseId/comments/:browseCommentId', browseComments.destroy);
 

var browseComments = require('../app/genControllers/browseComments.js');
 app.param('browseCommentId', browseComments.load);
app.post('/browses/:browseId/comments', auth.requiresLogin, browseComments.create);
app.get('/browses/:browseId/comments', auth.requiresLogin, browseComments.create);
app.delete('/browses/:browseId/comments/:browseCommentId', browseComments.destroy);
 

var browseRatings = require('../app/genControllers/browseRatings.js');
 app.param('browseRatingId', browseRatings.load);
app.post('/browse/:browseId/ratings', auth.requiresLogin, browseRatings.create);
app.get('/browse/:browseId/ratings', auth.requiresLogin, browseRatings.create);
app.delete('/browse/:browseId/ratings/:browseRatingId', browseRatings.destroy);
 

var browseRatings = require('../app/genControllers/browseRatings.js');
 app.param('browseRatingId', browseRatings.load);
app.post('/browses/:browseId/ratings', auth.requiresLogin, browseRatings.create);
app.get('/browses/:browseId/ratings', auth.requiresLogin, browseRatings.create);
app.delete('/browses/:browseId/ratings/:browseRatingId', browseRatings.destroy);
 

var browseLikes = require('../app/genControllers/browseLikes.js');
 app.param('browseLikeId', browseLikes.load);
app.post('/browse/:browseId/likes', auth.requiresLogin, browseLikes.create);
app.get('/browse/:browseId/likes', auth.requiresLogin, browseLikes.create);
app.delete('/browse/:browseId/likes/:browseLikeId', browseLikes.destroy);
 

var browseLikes = require('../app/genControllers/browseLikes.js');
 app.param('browseLikeId', browseLikes.load);
app.post('/browses/:browseId/likes', auth.requiresLogin, browseLikes.create);
app.get('/browses/:browseId/likes', auth.requiresLogin, browseLikes.create);
app.delete('/browses/:browseId/likes/:browseLikeId', browseLikes.destroy);
 

var browseCategories = require('../app/genControllers/browseCategories.js');
 app.param('browseCategoryId', browseCategories.load);
app.post('/browse/:browseId/categories', auth.requiresLogin, browseCategories.create);
app.get('/browse/:browseId/categories', auth.requiresLogin, browseCategories.create);
app.delete('/browse/:browseId/categories/:browseCategoryId', browseCategories.destroy);
 

var browseCategories = require('../app/genControllers/browseCategories.js');
 app.param('browseCategoryId', browseCategories.load);
app.post('/browses/:browseId/categories', auth.requiresLogin, browseCategories.create);
app.get('/browses/:browseId/categories', auth.requiresLogin, browseCategories.create);
app.delete('/browses/:browseId/categories/:browseCategoryId', browseCategories.destroy);
	 
	 app.param('photoId', photo.load); 

app.get('/photo', photo.index); 
 app.get('/photo/new', auth.requiresLogin, photo.new); 
 app.get('/photo/list', photo.list); 
   app.post('/photo', auth.requiresLogin, photo.create);
 app.get('/photo/:photoId', photo.show);
 app.get('/photo/:photoId/edit', photo.edit);
 app.put('/photo/:photoId', photo.update);
  app.delete('/photo/:photoId', photo.destroy);

app.param('photoId', photo.load); 

 app.get('/photos', photo.index); 
 app.get('/photos/new', auth.requiresLogin, photo.new); 
 app.get('/photos/list', photo.list); 
   app.post('/photos', auth.requiresLogin, photo.create);
 app.get('/photos/:photoId', photo.show);
 app.get('/photos/:photoId/edit', photo.edit);
 app.put('/photos/:photoId', photo.update);
  app.delete('/photos/:photoId', photo.destroy);


 

var photoComments = require('../app/genControllers/photoComments.js');
 app.param('photoCommentId', photoComments.load);
app.post('/photo/:photoId/comments', auth.requiresLogin, photoComments.create);
app.get('/photo/:photoId/comments', auth.requiresLogin, photoComments.create);
app.delete('/photo/:photoId/comments/:photoCommentId', photoComments.destroy);
 

var photoComments = require('../app/genControllers/photoComments.js');
 app.param('photoCommentId', photoComments.load);
app.post('/photos/:photoId/comments', auth.requiresLogin, photoComments.create);
app.get('/photos/:photoId/comments', auth.requiresLogin, photoComments.create);
app.delete('/photos/:photoId/comments/:photoCommentId', photoComments.destroy);
 

var photoRatings = require('../app/genControllers/photoRatings.js');
 app.param('photoRatingId', photoRatings.load);
app.post('/photo/:photoId/ratings', auth.requiresLogin, photoRatings.create);
app.get('/photo/:photoId/ratings', auth.requiresLogin, photoRatings.create);
app.delete('/photo/:photoId/ratings/:photoRatingId', photoRatings.destroy);
 

var photoRatings = require('../app/genControllers/photoRatings.js');
 app.param('photoRatingId', photoRatings.load);
app.post('/photos/:photoId/ratings', auth.requiresLogin, photoRatings.create);
app.get('/photos/:photoId/ratings', auth.requiresLogin, photoRatings.create);
app.delete('/photos/:photoId/ratings/:photoRatingId', photoRatings.destroy);
 

var photoLikes = require('../app/genControllers/photoLikes.js');
 app.param('photoLikeId', photoLikes.load);
app.post('/photo/:photoId/likes', auth.requiresLogin, photoLikes.create);
app.get('/photo/:photoId/likes', auth.requiresLogin, photoLikes.create);
app.delete('/photo/:photoId/likes/:photoLikeId', photoLikes.destroy);
 

var photoLikes = require('../app/genControllers/photoLikes.js');
 app.param('photoLikeId', photoLikes.load);
app.post('/photos/:photoId/likes', auth.requiresLogin, photoLikes.create);
app.get('/photos/:photoId/likes', auth.requiresLogin, photoLikes.create);
app.delete('/photos/:photoId/likes/:photoLikeId', photoLikes.destroy);
 

var photoCategories = require('../app/genControllers/photoCategories.js');
 app.param('photoCategoryId', photoCategories.load);
app.post('/photo/:photoId/categories', auth.requiresLogin, photoCategories.create);
app.get('/photo/:photoId/categories', auth.requiresLogin, photoCategories.create);
app.delete('/photo/:photoId/categories/:photoCategoryId', photoCategories.destroy);
 

var photoCategories = require('../app/genControllers/photoCategories.js');
 app.param('photoCategoryId', photoCategories.load);
app.post('/photos/:photoId/categories', auth.requiresLogin, photoCategories.create);
app.get('/photos/:photoId/categories', auth.requiresLogin, photoCategories.create);
app.delete('/photos/:photoId/categories/:photoCategoryId', photoCategories.destroy);
	 
	 app.param('coderId', coder.load); 

app.get('/coder', coder.index); 
 app.get('/coder/new', auth.requiresLogin, coder.new); 
 app.get('/coder/list', coder.list); 
   app.post('/coder', auth.requiresLogin, coder.create);
 app.get('/coder/:coderId', coder.show);
 app.get('/coder/:coderId/edit', coder.edit);
 app.put('/coder/:coderId', coder.update);
  app.delete('/coder/:coderId', coder.destroy);

app.param('coderId', coder.load); 

 app.get('/coders', coder.index); 
 app.get('/coders/new', auth.requiresLogin, coder.new); 
 app.get('/coders/list', coder.list); 
   app.post('/coders', auth.requiresLogin, coder.create);
 app.get('/coders/:coderId', coder.show);
 app.get('/coders/:coderId/edit', coder.edit);
 app.put('/coders/:coderId', coder.update);
  app.delete('/coders/:coderId', coder.destroy);


 

var coderComments = require('../app/genControllers/coderComments.js');
 app.param('coderCommentId', coderComments.load);
app.post('/coder/:coderId/comments', auth.requiresLogin, coderComments.create);
app.get('/coder/:coderId/comments', auth.requiresLogin, coderComments.create);
app.delete('/coder/:coderId/comments/:coderCommentId', coderComments.destroy);
 

var coderComments = require('../app/genControllers/coderComments.js');
 app.param('coderCommentId', coderComments.load);
app.post('/coders/:coderId/comments', auth.requiresLogin, coderComments.create);
app.get('/coders/:coderId/comments', auth.requiresLogin, coderComments.create);
app.delete('/coders/:coderId/comments/:coderCommentId', coderComments.destroy);
 

var coderRatings = require('../app/genControllers/coderRatings.js');
 app.param('coderRatingId', coderRatings.load);
app.post('/coder/:coderId/ratings', auth.requiresLogin, coderRatings.create);
app.get('/coder/:coderId/ratings', auth.requiresLogin, coderRatings.create);
app.delete('/coder/:coderId/ratings/:coderRatingId', coderRatings.destroy);
 

var coderRatings = require('../app/genControllers/coderRatings.js');
 app.param('coderRatingId', coderRatings.load);
app.post('/coders/:coderId/ratings', auth.requiresLogin, coderRatings.create);
app.get('/coders/:coderId/ratings', auth.requiresLogin, coderRatings.create);
app.delete('/coders/:coderId/ratings/:coderRatingId', coderRatings.destroy);
 

var coderLikes = require('../app/genControllers/coderLikes.js');
 app.param('coderLikeId', coderLikes.load);
app.post('/coder/:coderId/likes', auth.requiresLogin, coderLikes.create);
app.get('/coder/:coderId/likes', auth.requiresLogin, coderLikes.create);
app.delete('/coder/:coderId/likes/:coderLikeId', coderLikes.destroy);
 

var coderLikes = require('../app/genControllers/coderLikes.js');
 app.param('coderLikeId', coderLikes.load);
app.post('/coders/:coderId/likes', auth.requiresLogin, coderLikes.create);
app.get('/coders/:coderId/likes', auth.requiresLogin, coderLikes.create);
app.delete('/coders/:coderId/likes/:coderLikeId', coderLikes.destroy);
 

var coderCategories = require('../app/genControllers/coderCategories.js');
 app.param('coderCategoryId', coderCategories.load);
app.post('/coder/:coderId/categories', auth.requiresLogin, coderCategories.create);
app.get('/coder/:coderId/categories', auth.requiresLogin, coderCategories.create);
app.delete('/coder/:coderId/categories/:coderCategoryId', coderCategories.destroy);
 

var coderCategories = require('../app/genControllers/coderCategories.js');
 app.param('coderCategoryId', coderCategories.load);
app.post('/coders/:coderId/categories', auth.requiresLogin, coderCategories.create);
app.get('/coders/:coderId/categories', auth.requiresLogin, coderCategories.create);
app.delete('/coders/:coderId/categories/:coderCategoryId', coderCategories.destroy);
	

//end generated routes


  //api

   app.get('/api/getData', angularData.get);
   app.get('/api/sendWelcome', api.sendWelcome);
   app.post('/api/messageUs', api.messageUs);



  // comment routes
  app.param('commentId', comments.load);
  app.post('/articles/:id/comments', auth.requiresLogin, comments.create);
  app.get('/articles/:id/comments', auth.requiresLogin, comments.create);
  app.delete('/articles/:id/comments/:commentId', commentAuth, comments.destroy);


  // tag routes
  app.get('/tags/:tag', tags.index);


  /**
   * Error handling
   */

  app.use(function (err, req, res, next) {
    // treat as 404
    if (err.message
      && (~err.message.indexOf('not found')
      || (~err.message.indexOf('Cast to ObjectId failed')))) {
      return next();
    }
    console.error(err.stack);
    // error page
    res.status(500).render('500', { error: err.stack });
  });

  // assume 404 since no middleware responded
  app.use(function (req, res, next) {
    res.status(404).render('404', {
      url: req.originalUrl,
      error: 'Not found'
    });
  });
}
